### ISSUE TITLE
Crash on Android with current git HaxePunk and openfl 4.4.1 and lime 3.4.1

### ISSUE THREAD

**Issue by Jacic** [HaxePunk/HaxePunk#418]
I've been testing out the latest versions of openfl and lime with HaxePunk, and it seems there are still issues with compatability. My app compiles fine for android and linux, and works fine on linux, but it crashes immediately upon trying to create any image on android.

Terminal output:
``
11-12 20:16:27.508  5503  5610 E WindowManager: Performed 6 layouts in a row. Skipping
11-12 20:16:27.566 31867 29215 E AudioRecord-JNI: Error -4 during AudioRecord native read
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from ApplicationMain::main ApplicationMain.hx line 78
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from ApplicationMain::create ApplicationMain.hx line 93
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from lime.app.Preloader::create lime/app/Preloader.hx line 61
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.display.Preloader::start openfl/display/Preloader.hx line 95
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.display.Preloader::display_onComplete openfl/display/Preloader.hx line 145
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from lime.app.Preloader::start lime/app/Preloader.hx line 284
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from lime.app._Event_Void_Void::dispatch lime/app/Event.hx line 145
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from ApplicationMain::init ApplicationMain.hx line 328
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from ApplicationMain::start ApplicationMain.hx line 344
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from Main::main Main.hx line 30
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from Main::new Main.hx line 7
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from com.haxepunk.Engine::new com/haxepunk/Engine.hx line 94
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.display.DisplayObjectContainer::addChild openfl/display/DisplayObjectContainer.hx line 46
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.display.DisplayObjectContainer::addChildAt openfl/display/DisplayObjectContainer.hx line 97
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.display.DisplayObjectContainer::__dispatchChildren openfl/display/DisplayObjectContainer.hx line 326
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.display.DisplayObject::__dispatchEvent openfl/display/DisplayObject.hx line 354
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 213
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from com.haxepunk.Engine::onStage com/haxepunk/Engine.hx line 264
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from Main::init Main.hx line 21
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from TitleScene::new TitleScene.hx line 120
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from com.haxepunk.graphics.atlas.AtlasData::new com/haxepunk/graphics/atlas/AtlasData.hx line 86
11-12 20:16:27.631 31210 31238 E HXCPP   : Called from com.haxepunk.graphics.atlas.renderer.TileShaderRenderer::new com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx line 145
11-12 20:16:27.632 31210 31238 E HXCPP   : Called from com.haxepunk.graphics.atlas.renderer._TileShaderRenderer.TileShader::new com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx line 70
11-12 20:16:27.632 31210 31238 E Exception: Error compiling fragment shader
11-12 20:16:27.651 31210 31210 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
11-12 20:16:28.058   370   370 E qdoverlay: Failed to call ioctl MSMFB_OVERLAY_SET err=Device or resource busy
11-12 20:16:28.058   370   370 E qdoverlay: MdssRot commit failed!
11-12 20:16:28.058   370   370 E qdoverlay: == Dump MdssRot start ==
11-12 20:16:28.058   370   370 E qdoverlay: == Dump OvFD fd=109 path=/dev/graphics/fb0 start/end ==
11-12 20:16:28.058   370   370 E qdoverlay: == Dump OvMem start ==
11-12 20:16:28.058   370   370 E qdoverlay: fd=-1 addr=0xffffffffffffffff type=0 bufsz=0 AlignedBufSz=0
11-12 20:16:28.058   370   370 E qdoverlay: == Dump OvMem end ==
``

I tested a few things, and there seems to be a problem with rendering/creating images, Image, Spritemap, Emitter, etc.

**Comment by matrefeytontias** [comment]
The interesting part of this all being (a bit prettyfied):
```
11-12 20:16:27.632 31210 31238 E HXCPP : Called from com.haxepunk.graphics.atlas.renderer.TileShaderRenderer::new com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx line 145
11-12 20:16:27.632 31210 31238 E HXCPP : Called from com.haxepunk.graphics.atlas.renderer._TileShaderRenderer.TileShader::new com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx line 70
11-12 20:16:27.632 31210 31238 E Exception: Error compiling fragment shader 11-12 20:16:27.651 31210 31210 E libEGL : call to OpenGL ES API with no current context (logged once per thread)
11-12 20:16:28.058 370 370 E qdoverlay: Failed to call ioctl MSMFB_OVERLAY_SET err=Device or resource busy
```

**Comment by Jacic** [comment]
Yeah, that's the most relevant part, but I wanted to include some of the surrounding output in case someone makes a connection I missed.

**Comment by bendmorris** [comment]
This is probably an issue with how I implemented TileShaderRenderer. I have a new hardware renderer in progress for HaxePunk 4. I'll see if backporting that fixes the issue.

**Comment by Jacic** [comment]
Unfortunately, the problem persists even with the new renderer changes

```
11-27 16:58:08.997 26736 26768 E HXCPP   : Called from ApplicationMain::main ApplicationMain.hx line 78
11-27 16:58:08.997 26736 26768 E HXCPP   : Called from ApplicationMain::create ApplicationMain.hx line 234
11-27 16:58:08.997 26736 26768 E HXCPP   : Called from lime.app.Application::exec lime/app/Application.hx line 212
11-27 16:58:08.997 26736 26768 E HXCPP   : Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 136
11-27 16:58:08.997 26736 26768 E HXCPP   : Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 373
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from lime.app._Event_Void_Void::dispatch lime/app/Event.hx line 145
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from *::_Function_2_1 openfl/display/Stage.hx line 202
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl.display.Stage::render openfl/display/Stage.hx line 810
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl._internal.renderer.opengl.GLRenderer::render openfl/_internal/renderer/opengl/GLRenderer.hx line 121
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 718
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 718
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 718
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 718
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from openfl.display.OpenGLView::__renderGL openfl/display/OpenGLView.hx line 195
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from com.haxepunk.graphics.atlas.SceneSprite::renderScene com/haxepunk/graphics/atlas/SceneSprite.hx line 58
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from com.haxepunk.graphics.atlas.HardwareRenderer::render com/haxepunk/graphics/atlas/HardwareRenderer.hx line 162
11-27 16:58:08.998 26736 26768 E HXCPP   : Called from com.haxepunk.graphics.atlas._HardwareRenderer.TextureShader::new com/haxepunk/graphics/atlas/HardwareRenderer.hx line 72
11-27 16:58:08.998 26736 26768 E Exception: Error compiling vertex shader
11-27 16:58:09.017 26736 26736 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
```

**Comment by bendmorris** [comment]
Sorry, didn't mean to close without testing - I think GitHub did that automatically when I merged.

**Comment by Jacic** [comment]
I was going to ask about the status of this issue, and reopen it, but it seems I'm not able to do so.

Could you reopen the issue @bendmorris, or would you like me to create a new issue and reference this one?

**Comment by bendmorris** [comment]
Still planning on looking into this before release. Don't have a handy Android test device at the moment.

**Comment by Jacic** [comment]
I'd be willing to test my project and say a sample project on a couple devices if you'd like.

**Comment by Jacic** [comment]
The latest render changes have fixed the crash, great work!

**Comment by bendmorris** [comment]
Great, thanks for confirming.
